---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localpathprovisioner
  annotations:
{{- if .Values.storageclass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
    kubernetes.io/description: Local path provisioner storage class
provisioner: rancher.io/local-path
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode | quote }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy | quote }}
