---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localpathprovisioner
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageclass.isDefault | default "true" | quote }}
    kubernetes.io/description: Local path provisioner storage class
provisioner: rancher.io/local-path
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode | quote }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy | quote }}
