apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: awsebscsiprovisioner
  annotations:
    kubernetes.io/description: AWS EBS CSI provisioner StorageClass
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageclass.isDefault | default "true" | quote }}
provisioner: ebs.csi.aws.com
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode | quote }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy | quote }}
