---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-volume-provisioner-configmap
  namespace: {{ .Release.Namespace }}
data:
  storageClassMap: |
    {{- range .Values.storageclasses }}
    localvolumeprovisioner-{{ .name }}:
      hostDir: /mnt/{{ .name }}
      mountDir: /mnt/{{ .name }}
      blockCleanerCommand:
       - "/scripts/shred.sh"
       - "2"
      volumeMode: Filesystem
      fsType: ext4
    {{- end }}
