---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opsportal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: "before-hook-creation"
