---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  name: {{ template "opsportal.fullname" . }}-addons
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
{{- with .Values.opsportal.ingress.paths }}
{{ toYaml . | indent 10 }}
{{- end }}
