{{- if .Values.landing.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opsportal-landing
  name: opsportal-landing
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: opsportal-landing
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: opsportal-landing
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: Path
  name: opsportal-landing
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: opsportal-landing
              servicePort: 80
            path: /landing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opsportal-landing
  name: opsportal-landing
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: opsportal-landing
  template:
    metadata:
      labels:
        app: opsportal-landing
    spec:
      containers:
        - name: opsportal-landing
          image: nginx:1.15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: landing-html
              mountPath: /usr/share/nginx/html
            - name: landing-conf
              mountPath: /etc/nginx
      volumes:
        - name: landing-html
          configMap:
            name: opsportal-landing-html
        - name: landing-conf
          configMap:
            name: opsportal-landing-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: opsportal-landing-html
  namespace: {{ .Release.Namespace }}
  labels:
    app: opsportal-landing
data:
  index.html: |
    <!DOCTYPE html><html lang="en"><head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <meta http-equiv="X-UA-Compatible" content="ie=edge"> <title>Konvoy Landing</title> <style> * { box-sizing: border-box; } html, body { color: #1B2029; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica', 'Arial', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'; font-size: 14px; font-weight: 400; height: 100%; margin: 0; padding: 0; } #app { height: 100%; background-color: #F7F8F9; display: flex; align-items: center; justify-content: center; } .landing-container { display: flex; flex-direction: column; align-items: center; width: 100%; max-width: 350px; } .card { width: 100%; text-align: center; background-color: white; padding: 32px; border: 1px solid #DADDE2; border-radius: 4px; margin: 24px 0; } .heading { font-weight: 500; font-size: 18px; margin: 0; padding-bottom: 12px; } .button { display: block; background-color: #E1E3E7; border-radius: 4px; padding: 8px; margin-top: 16px; color: inherit; text-decoration: none; cursor: pointer; font-weight: 500; } .button:hover { background-color: #cacccf; } .privacy { font-size: 12px; margin-top: 12px; color: #76797E; text-align: center; } .link { color: inherit; } .link:hover { color: #6a6c71; } </style></head><body> <div id="app"> <div class="landing-container"> <div class="card"> <h1 class="heading">Welcome to Konvoy!</h1> <a href="/ops/portal/" class="button">Launch Console</a> <a href="/token" class="button">Generate Kubectl Token</a> </div> <div class="privacy"> By logging in you understand that we will process personal information in accordance with our <a href="https://mesosphere.com/privacy/" class="link">Privacy Policy</a> <div></div> </div> </div> </div></body></html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsportal-landing-conf
  namespace: {{ .Release.Namespace }}
  labels:
    app: opsportal-landing
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;
    events {
        worker_connections 1024;
    }
    http {
      server {
        access_log /dev/stdout;
        listen 80;
        root /usr/share/nginx/html;
        location / {
            try_files $uri /index.html;
        }
        location = /index.html {
            expires 30s;
        }
      }
    }
{{- end }}
