apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ template "opsportal.fullname" . }}-token
  annotations:
    kubernetes.io/service-account.name: {{ template "opsportal.fullname" . }}
  namespace: {{ .Release.Namespace }}
