bearerproxy:
  port: 9091
  image:
    repository: "quay.io/joejulian/bearerproxy"
    tag: "latest"
    pullPolicy: "Always"

landing:
  enabled: true

# these secrets are created via hooks
secrets:
  create: true
  name: ops-portal-credentials
  image:
    repository: "kubeaddons/addon-initializer"
    tag: "opsportal-2"

opsportal:
  ingress:
    paths:
      # kubernetes-dashboard
      - backend:
          serviceName: bearerproxy
          servicePort: 9091
        path: /ops/portal/kubernetes
      # kibana
      - backend:
          serviceName: kibana-kubeaddons
          servicePort: 5601
        path: /ops/portal/kibana
      # grafana
      - backend:
          serviceName: prometheus-kubeaddons-grafana
          servicePort: 3000
        path: /ops/portal/grafana
      # prometheus
      - backend:
          serviceName: prometheus-kubeaddons-prom-prometheus
          servicePort: 9090
        path: /ops/portal/prometheus
      # alertmanager
      - backend:
          serviceName: prometheus-kubeaddons-prom-alertmanager
          servicePort: 9093
        path: /ops/portal/alertmanager
      # traefik
      - backend:
          serviceName: traefik-kubeaddons-dashboard
          servicePort: 80
        path: /ops/portal/traefik
