---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kommander.fullname" . }}
  labels:
    app: {{ template "kommander.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: traefik
{{- if (eq "konvoy" .Values.mode) }}
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/priority: "1"
{{- else }}
    traefik.frontend.rule.type: {{ .Values.ingress.traefikFrontendRuleType }}
    {{- with .Values.ingress.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ .Values.service.name }}
              servicePort: 80
            path: {{ .Values.ingress.path }}
