image:
  repository: mesosphere/kommander
  tag: 1.47.2
  pullPolicy: IfNotPresent
replicas: 1
logoutRedirectPath: /

# Mode must be either production|konvoy
mode: production

extraInitContainers:

resources:
  requests:
    memory: "128Mi"
    cpu: "1000m"
  limits:
    memory: "512Mi"
    cpu: "2000m"

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 3
livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 3

### This must match the serviceName set in the ingress backend below
service:
  name: kommander

ingress:
  traefikFrontendRuleType: PathPrefixStrip
  # extraAnnotations:
  #   ingress.kubernetes.io/foo: bar
  path: /ops/portal/kommander
